trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "EcoRide.Backend/*"
    exclude:
      - "EcoRide.Backend/pipe/*"
      - "*.md"

pr: none

resources:
  repositories:
    - repository: Templates
      type: git
      name: MyPortal3e.Pipelines.Templates

pool:
  name: PoolDocker
  demands: dotnet

extends:
  template: dotnet/V1/service-deploy.yaml@Templates
  parameters:
    SourceDirectory: "$(Build.SourcesDirectory)/EcoRide.Backend"
    projectFile: "**/EcoRide.Backend.WebApi.csproj"
    testProjectFile: "**/EcoRide.Backend.Tests.csproj"
    publishTargetFramework: "net8.0"
    DotNetSdkVersion: 8.0.416
    sonarCloudOrganization: "clauger3e-sonarcloud"
    sonarCloudProjectKey: "halajarin_EcoRide"
    sonarCloudProjectName: "EcoRide.Backend"
    runTests: True
    runPostmanTests: False
    imageName: "ecoride/backend-api"
    applicationName: "ecoride-backend-api"
    gitOpsPath: dev/ecoride-backend
