trigger:
  branches:
    include:
      - main
      - dev
  paths:
    exclude:
      - "pipe/*"
      - "README.md"
      - ".gitignore"
      - "*.md"

pr: none

resources:
  repositories:
    - repository: Templates
      type: git
      name: MyPortal3e.Pipelines.Templates

pool:
  name: PoolDocker
  demands: npm

extends:
  template: angular/V1/service-deploy.yaml@Templates
  parameters:
    sourceDirectory: "$(Build.SourcesDirectory)/EcoRide.Frontend"
    projectName: "EcoRide.Frontend"
    imageName: "ecoride/frontend"
    sonarCloudOrganization: "clauger3e-sonarcloud"
    sonarCloudProjectKey: "halajarin_EcoRide_Frontend"
    sonarCloudProjectName: "EcoRide.Frontend"
    gitOpsPath: dev/ecoride-frontend
